export {default as heroCompImg} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
export {default as lotionImg} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
export {default as shampoImg} from './images/front-view-black-plastic-bottle-from-shampoo-with-pink-strip.jpg';
export {default as sectImg} from './images/zero-waste-beauty-products.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';
// export {default as heroCompIm} from './images/single-glass-bottle-filled-with-clear-liquid-generated-by-ai.jpg';